### DISCUSSION TITLE
Too many redirects when using a nginx reverce proxy

### DISCUSSION THREAD

**Discussion by denisbondar** [nfrastack/container-freescout#179] [Q&A] [answered]
Hi, Dave!
Hi, community!

I can't solve the problem with endless redirects to https when using freescout in a container preceded by a reverse proxy.

The scheme is simple: I have nginx on the same host, which performs SSL functions and just proxies requests to other containers. I use several containers this way and everything works fine there. But the container with freescout I am having trouble getting up and running.

Here is the server configuration of my nginx server:
```
server {
    listen       443 ssl;
    server_name  my.domain.name;
    include      ssl.conf;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass  http://127.0.0.1:8088;
    }
}
```

And here is the configuration of the freescout container:
```
services:
  freescout:
    image: tiredofit/freescout:latest_php8.2
    environment:
      SITE_URL: https://my.domain.name
      FORCE_HTTPS: True
    volumes:
      - ./scout/logs:/www/logs
      - ./scout/data:/data
    ports:
      - 127.0.0.1:8088:80
    depends_on:
      - db
    restart: unless-stopped
    logging:
      driver: local
```

I removed some docker-compose environment variables, such as database connection settings, etc., so as not to clutter up the text.
