### DISCUSSION TITLE
Really struggling getting everything up and running with docker compose and portainer

### DISCUSSION THREAD

**Discussion by dillon-kondrick** [nfrastack/container-freescout#84] [Q&A]
Having an issue with using the docker-compose file (no proxy) and Portainer stacks.

I think my issue boils down to the SITE_URL environment variable.  I don't have a site that I can use, I was only hoping to test it out internally and access by IP address.  However, if I enter in the IP address into that field, when I navigate to the Freescout login page, it looks off, and errors on login.  Then the link to the homepage shows a url with duplicate IP address info like so:

The log for the freescout-app stops here:

```
2022-08-18.15:10:32 [STARTING] ** [monitoring] [1] Starting Zabbix Agent (modern) 6.2.1

2022-08-18.15:10:32 [DEBUG] ** [scheduling] Container: Getting defaults for /assets/defaults/30-freescout

2022-08-18.15:10:32 [DEBUG] ** [scheduling] Checking to see if container initialization scripts have completed

2022-08-18.15:10:32 [DEBUG] ** [scheduling] Checking to see if service has initialized

2022-08-18.15:10:32 [DEBUG] ** [scheduling] [logrotate] Setting Logrotate retention days after all services have finished initializing

2022-08-18.15:10:32 [DEBUG] ** [scheduling] [logrotate] Moving files from /assets/logrotate to /etc/logrotate.d

2022-08-18.15:10:32 [DEBUG] ** [scheduling] Parsing all files from /assets/cron/

Starting Zabbix Agent 2 (6.2.1)

Zabbix Agent2 hostname: [freescout-app]

Press Ctrl+C to exit.

2022-08-18.15:10:32 [STARTING] ** [scheduling] [1] Starting cron

```

---

And the hyperlink to the Homepage for Freescout is showing like  this:
![image](https://user-images.githubusercontent.com/53623543/185431284-9a14dcb7-dca1-42dc-a950-daaa00f22a16.png)

![image](https://user-images.githubusercontent.com/53623543/185430642-0ed61fa2-ccb4-4ec6-ae17-c6dc2c46adfc.png)

---

Here is my docker compose contents

```
version: '2'

services:
  freescout-app:
    image: tiredofit/freescout
    container_name: freescout-app
    ports:
    - 29583:80
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    - CONTAINER_NAME=freescout-app
    
    - DB_HOST=freescout-db
    - DB_NAME=freescout
    - DB_USER=freescout
    - DB_PASS=freescout

    - SITE_URL=192.168.1.63
    - ADMIN_EMAIL=admin@admin.com
    - ADMIN_PASS=freescout
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=TRUE
    - TIMEZONE=America/CHICAGO
    - CONTAINER_LOG_LEVEL=DEBUG
    

    restart: always

  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - CONTAINER_NAME=freescout-db
      - CONTAINER_LOG_LEVEL=DEBUG
    restart: always

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always
```
